// Local-model conversation, ad galleries, and explicit bulk message submissions.
let localService=false;
let conversation=JSON.parse(localStorage.getItem('chris-conversation')||'[]');
let transferredBatch=null;
if(location.hash.startsWith('#message-batch=')){try{transferredBatch=JSON.parse(decodeURIComponent(location.hash.slice(15)));history.replaceState(null,'',location.pathname);}catch(e){}}
let searchSpec=JSON.parse(localStorage.getItem('chris-search-spec')||'null');
const localAppURL='http://kms-mac-mini-1.tail016811.ts.net:8766/';
const expectsLocalService=['localhost','127.0.0.1',new URL(localAppURL).hostname].includes(location.hostname);
async function localCall(path,data){
 const response=await originalFetch('/local/'+path,{signal:AbortSignal.timeout(path==='assistant'?190000:60000),method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-Chris-List':'local'}:{},body:data?JSON.stringify(data):undefined});
 if(!response.ok)throw Error((await response.json()).error||'Mac service unavailable');return response.json();
}
function saveChat(){localStorage.setItem('chris-conversation',JSON.stringify(conversation));localStorage.setItem('chris-search-spec',JSON.stringify(searchSpec));}
function chatPanel(){
 const panel=document.createElement('div');panel.className='panel';panel.id='search-assistant';
 panel.innerHTML='<b>What do you want to find?</b><p class="small">Describe the item and your must-haves. Refine the search together, then approve it.</p><div id="chat-history"></div><form id="chat-form"><textarea id="chat-input" required placeholder="I need a machine that holds a pen and cutter together, fits inside…"></textarea><button '+(!localService?'disabled':'')+'>Discuss with local AI</button></form><p class="small" id="chat-status"></p><div id="search-review"></div>';
 const history=panel.querySelector('#chat-history');for(const message of conversation){const p=document.createElement('p');p.textContent=(message.role==='user'?'You: ':'Chris List: ')+message.content;history.append(p);}
 panel.querySelector('#chat-status').innerHTML=localService?'Runs on this Mac with Ollama. No paid AI tokens; chat works without internet.':'<a href="'+localAppURL+'">Open private app for AI and sending</a> (works on your phone with Tailscale; Mac mini must be awake), or <a href="http://127.0.0.1:8766/">open directly on this Mac</a>. The public site shows saved scan results.';
 panel.querySelector('#chat-form').onsubmit=async e=>{e.preventDefault();const input=panel.querySelector('#chat-input'),button=panel.querySelector('button'),status=panel.querySelector('#chat-status');const text=input.value.trim();if(!text)return;conversation.push({role:'user',content:text});saveChat();input.value='';button.disabled=true;status.textContent='Local model is thinking…';try{const result=await localCall('assistant',{messages:conversation});conversation.push({role:'assistant',content:result.reply});searchSpec=result.spec;saveChat();await load();}catch(error){status.textContent=error.message;button.disabled=false;}};
 if(searchSpec){const review=panel.querySelector('#search-review');review.innerHTML='<h3>Review search</h3><label>Marketplace keywords<input id="spec-query"></label><label>All requirements<textarea id="spec-description"></textarea></label><label>Required phrases (comma separated)<input id="spec-include"></label><label>Exclude phrases (comma separated)<input id="spec-exclude"></label><label>Hide asking prices above $ (optional)<input id="spec-max" type="number" min="0"></label><label>Priority<select id="spec-priority"><option value="primary">Primary</option><option value="secondary">Lower priority</option></select></label><p class="small">Keywords, required/excluded phrases and price limit are enforced. Other specifics stay attached for verification; they are not assumed true.</p><button id="approve-search">Approve and start searching</button><button id="new-search">Start another search</button>';
 for(const [id,value] of [['query',searchSpec.query],['description',searchSpec.description],['include',(searchSpec.include||[]).join(', ')],['exclude',(searchSpec.exclude||[]).join(', ')],['max',searchSpec.price_max??''],['priority',searchSpec.priority||'primary']])review.querySelector('#spec-'+id).value=value||'';
 review.querySelector('#approve-search').onclick=async()=>{try{const value=id=>review.querySelector('#spec-'+id).value;const spec={query:value('query'),description:value('description'),include:value('include').split(',').map(s=>s.trim()).filter(Boolean),exclude:value('exclude').split(',').map(s=>s.trim()).filter(Boolean),price_max:value('max')===''?null:Number(value('max')),priority:value('priority')};await localCall('watch',spec);await api('/api/watch',{description:spec.description||spec.query});const result=await localCall('scan',{});alert(result.status);conversation=[];searchSpec=null;saveChat();load();}catch(e){alert(e.message);}};
 review.querySelector('#new-search').onclick=()=>{conversation=[];searchSpec=null;saveChat();load();};}
 return panel;
}
// Explicit review travels with the exact listing and draft; it is validated again by the server.
function listingReviewForm(row){
 const form=document.createElement('fieldset');form.className='listing-review';
 form.innerHTML='<legend>Review this listing before sending</legend><label>Your name<input data-review="approver" autocomplete="name"></label><label>Seller name shown on the ad<input data-review="seller"></label><label>Intended use<input data-review="intended_use" placeholder="What is this item for?"></label><label>Requirement set<select data-review="purpose"><option value="enclosure">Caricature enclosure: 64 × 30 inches usable inside</option><option value="machine">Drawing/cutting machine</option><option value="other">Other use — describe above</option></select></label><label>Message purpose<select data-review="intent"><option value="offer">Offer or pickup request</option><option value="inquiry">Question only — no offer or pickup commitment</option></select></label><label>Dimension type<select data-review="dimension_basis"><option value="unknown">Not verified</option><option value="overall">Overall / exterior</option><option value="usable_inside">Usable interior</option></select></label><label>Width in inches<input data-review="width" type="number" min="0" step="any"></label><label>Depth in inches<input data-review="depth" type="number" min="0" step="any"></label><label>Evidence or seller measurement<textarea data-review="evidence" placeholder="Where did the measurements come from?"></textarea></label><p>Exterior dimensions do not prove interior fit. Unknown fit allows questions; an offer needs fit evidence or an explicit exception.</p><label>Approved exception, if needed<textarea data-review="exception_reason" placeholder="Explain why proceeding despite incompatible or unknown fit is appropriate."></textarea></label><label><input data-review="confirmed" type="checkbox"> I reviewed this listing, its seller, and the exact message above and approve sending it.</label>';
 if(!(row.watch_ids||[]).includes('primary-enclosure'))form.querySelector('[data-review="purpose"]').value=row.machine_fit?.is_machine?'machine':'other';
 form.addEventListener('input',e=>{if(e.target.dataset.review!=='confirmed')form.querySelector('[data-review="confirmed"]').checked=false;});
 return form;
}
function readListingReview(preview){
 const review={requirements_revision:'enclosure-64x30-v1'};
 for(const field of preview.querySelectorAll('[data-review]'))review[field.dataset.review]=field.type==='checkbox'?field.checked:field.value;
 return review;
}
function bulkMessage(){
 closeModal();const rows=state.listings.filter(x=>selected.has(x.id));if(!rows.length)return alert('Select one or more ads first.');
 const overlay=document.createElement('div');overlay.className='modal-back';overlay.id='modal';overlay.innerHTML='<div class="modal" role="dialog"><button class="close" onclick="closeModal()">×</button><h2>Message '+rows.length+' selected ads</h2><label>Message option<select id="bulk-option"><option value="free">Free pickup for art project</option><option value="offer">Make an offer</option><option value="tools">Ask about pen + cutter</option><option value="custom">Write my own</option></select></label><label>Offer amount<input id="bulk-offer" type="number" min="0"></label><textarea id="bulk-template"></textarea><p class="small">Use {title} and {offer}. Edit any individual message below.</p><button id="apply-template">Apply to selected ads</button><div id="bulk-previews"></div><button id="send-batch">Send selected seller messages</button><p id="bulk-result" class="small" role="status" aria-live="polite"></p></div>';document.body.append(overlay);
 const batch=transferredBatch;transferredBatch=null;
 const template=overlay.querySelector('#bulk-template');
 const templates={free:'Hi! I’m building a local art project. If this is still available and you mainly need it out of the way, I’d love to pick it up free. Please keep me in mind if it doesn’t sell.',offer:'Hi! I’m interested in your {title} for an art project. Would you consider ${offer}? I can arrange pickup.',tools:'Hi! Does your {title} hold a pen and cutter at the same time and draw then cut without manually swapping tools? Are both tools included? Could you confirm the working width and overall machine width?',custom:''};
 function apply(){const amount=overlay.querySelector('#bulk-offer').value;overlay.querySelector('#bulk-previews').replaceChildren();for(const row of rows){const div=document.createElement('div');div.className='message-preview';const request=batch?.find(x=>x.id===row.id);if(request?.staff_event)div.dataset.staffEvent=request.staff_event;const label=document.createElement('p');label.textContent=row.platform+' · '+row.title;const text=document.createElement('textarea');text.dataset.listing=row.id;text.value=template.value.replaceAll('{title}',row.title).replaceAll('{offer}',amount||'[offer amount]');const copy=document.createElement('button');copy.textContent='Copy message';copy.onclick=()=>copyText(text.value);const open=document.createElement('a');open.href=row.url;open.target='_blank';open.rel='noopener';open.textContent='Open ad';div.append(label,text,copy,open,listingReviewForm(row));if(request?.staff_text){const source=document.createElement('p');source.textContent='Staff request: '+request.staff_text;div.prepend(source);}text.addEventListener('input',()=>{div.querySelector('[data-review="confirmed"]').checked=false;});overlay.querySelector('#bulk-previews').append(div);}}
 template.value=batch?.some(x=>x.staff_event)?templates.custom:templates.free;apply();if(batch){for(const t of overlay.querySelectorAll('[data-listing]')){const item=batch.find(x=>x.id===t.dataset.listing);if(typeof item?.text==='string')t.value=item.text;}}overlay.querySelector('#bulk-option').onchange=e=>{template.value=templates[e.target.value];apply();};overlay.querySelector('#apply-template').onclick=apply;
 const sendButton=overlay.querySelector('#send-batch'),out=overlay.querySelector('#bulk-result');
 sendButton.before(out);
 function report(text){out.textContent=text;out.scrollIntoView({block:'nearest'});}
 const descriptions={queued:'Queued — not sent yet',sending:'Sending — checking delivery',sent:'Sent — delivery verified',manual_send_required:'NOT SENT — this platform was not connected',needs_connection:'NOT SENT — Chrome connection required',needs_login:'NOT SENT — platform sign-in required',needs_review:'NOT SENT — review required',delivery_unconfirmed:'Delivery uncertain — check the platform before retrying',failed:'NOT SENT — failed'};
 function showJobs(jobs){report(jobs.map(x=>x.title+': '+(descriptions[x.status]||x.status)+(x.detail?'\n'+x.detail:'')).join('\n\n'));}
 if(localService){sendButton.disabled=true;report('Checking sending connection…');localCall('message-preflight',{ids:rows.map(x=>x.id)}).then(check=>{report(check.detail);sendButton.disabled=false;sendButton.textContent=check.ready?'Send selected seller messages':'Check connection and send';}).catch(e=>{report(e.message);sendButton.disabled=false;});}
 else{sendButton.textContent=expectsLocalService?'Reconnect to private app':'Open private app to review & send';report(expectsLocalService?'The Mac service is not responding yet. Reconnect to reopen these drafts; nothing will be sent automatically.':'Open the private app to review these drafts and send through your marketplace accounts. You can stay on this phone: connect Tailscale and keep the Mac mini awake. Opening the app does not send messages.');}
 sendButton.onclick=async()=>{
  const messages=[...overlay.querySelectorAll('[data-listing]')].map(t=>{const row=rows.find(r=>r.id===t.dataset.listing);return {id:row.id,url:row.url,title:row.title,text:t.value,staff_event:t.closest('.message-preview').dataset.staffEvent||null,review:readListingReview(t.closest('.message-preview'))};});
  if(messages.some(x=>!x.text.trim()||x.text.includes('[offer amount]')))return report('Not sent. Fill in the offer and message first.');
  if(!localService){location.href=localAppURL+'#message-batch='+encodeURIComponent(JSON.stringify(messages));return;}
  if(messages.some(x=>!x.review.confirmed||!x.review.approver.trim()||!x.review.seller.trim()||!x.review.intended_use.trim()))return report('Not sent. Complete the listing review, your name, seller, intended use and approval checkbox for each message.');
  sendButton.disabled=true;report('Submitting selected messages…');
  try{const result=await localCall('messages',{messages});showJobs(result.messages);sendButton.textContent='Batch submitted — see delivery results';const ids=new Set(result.messages.map(x=>x.id));
   const timer=setInterval(async()=>{if(!overlay.isConnected){clearInterval(timer);return;}try{const status=await localCall('status');if(status.message_queue?.ready===false)throw new Error(status.message_queue.detail);const jobs=status.messages.filter(x=>ids.has(x.id));showJobs(jobs);if(jobs.every(x=>!['queued','sending'].includes(x.status))){clearInterval(timer);sendButton.disabled=false;sendButton.textContent='Retry messages that were not sent';}}catch(e){report('Could not refresh delivery status: '+e.message);clearInterval(timer);sendButton.disabled=false;}},2000);
  }catch(e){report(e.message);sendButton.disabled=false;sendButton.textContent='Check connection and send';}
 };

}
async function copyText(text){if(navigator.clipboard){await navigator.clipboard.writeText(text);return;}const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();document.execCommand('copy');t.remove();}
const workspaceRender=render;
render=function(){workspaceRender();const aside=document.querySelector('aside');aside.prepend(chatPanel());const watch=aside.querySelector('#wf')?.closest('.panel');if(watch){const heading=watch.querySelector('b');if(heading)heading.textContent='Quick keyword search';if(localService){watch.querySelector('#wf').onsubmit=async e=>{e.preventDefault();const query=watch.querySelector('#desc').value.trim();try{await localCall('watch',{query,description:query});await api('/api/watch',{description:query});await localCall('scan',{});load();}catch(err){alert(err.message);}};for(const b of watch.querySelectorAll('button'))if(b.textContent==='Add description to automatic scans')b.remove();}}
 const old=document.querySelector('.bar button');for(const b of document.querySelectorAll('.bar button'))if(b.textContent==='review selected messages'){b.textContent='Message selected ads';b.onclick=bulkMessage;}
 const all=document.createElement('button');all.textContent='Select all primary ads';all.onclick=()=>{visibleListings().filter(x=>x.priority!=='secondary').forEach(x=>selected.add(x.id));load();};document.querySelector('.bar').append(all);const none=document.createElement('button');none.textContent='Clear selection';none.onclick=()=>{selected.clear();load();};document.querySelector('.bar').append(none);
 if(localService&&transferredBatch){for(const x of transferredBatch)if(state.listings.some(r=>r.id===x.id))selected.add(x.id);if(selected.size)setTimeout(bulkMessage,0);}
 if(localService){const connection=document.createElement('button');connection.textContent='Check Facebook sending connection';connection.onclick=async()=>{connection.disabled=true;try{const info=await localCall('chrome-check',{});alert(info.login_required?'Chrome connection works; sign in to Facebook in Chrome before sending.':'Chrome connection works. Facebook opened without a password form; review your selected messages before sending.');}catch(e){alert(e.message);}finally{connection.disabled=false;}};document.querySelector('.bar').append(connection);const scan=document.createElement('button');scan.textContent='Scan now on this Mac';scan.onclick=async()=>{try{alert((await localCall('scan',{})).status);}catch(e){alert(e.message);}};document.querySelector('.bar').append(scan);}
};
const galleryOpen=openItem;
openItem=function(id){galleryOpen(id);const modal=document.querySelector('.modal');if(!modal)return;const row=state.listings.find(x=>x.id===id);const selectedBox=document.createElement('label');const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.style.width='auto';checkbox.checked=selected.has(id);checkbox.onchange=()=>checkbox.checked?selected.add(id):selected.delete(id);selectedBox.append(checkbox,document.createTextNode(' Select this ad for messaging'));modal.prepend(selectedBox);const message=document.createElement('button');message.textContent='Message this ad';message.onclick=()=>{selected.clear();selected.add(id);bulkMessage();};selectedBox.after(message);
 const gallery=document.createElement('div');gallery.className='ad-gallery';const status=document.createElement('p');status.className='small';const known=row.images?.length?row.images:row.image?[row.image]:[];function show(images){gallery.replaceChildren();for(const src of [...new Set(images)]){if(!/^https?:\/\//.test(src))continue;const a=document.createElement('a');a.href=src;a.target='_blank';a.rel='noopener';const img=document.createElement('img');img.src=src;img.alt=row.title;img.loading='lazy';a.append(img);gallery.append(a);}}show(known);modal.querySelector('.detail').after(gallery,status);
 status.textContent=row.photo_status||'Search photo only; fetching the ad gallery requires the Mac app.';
 if(localService){status.textContent='Loading ad photos…';localCall('photos?id='+encodeURIComponent(id)).then(async data=>{show(data.images);status.textContent=data.detail;await api('/api/listing/update',{id,images:data.images,photo_status:data.detail});}).catch(e=>status.textContent='Gallery unavailable: '+e.message);}
};
localCall('status').then(()=>{localService=true;load();}).catch(()=>{});
setInterval(async()=>{if((!localService&&!expectsLocalService)||document.visibilityState!=='visible')return;try{const info=await localCall('status');if(!localService){localService=true;await load();}showAlertHealth(info.alerts);showStaffRequests(info);let panel=document.querySelector('#delivery-status');if(!panel){panel=document.createElement('details');panel.id='delivery-status';document.querySelector('.bar').append(panel);}panel.replaceChildren();const title=document.createElement('summary');title.textContent='Message delivery status';panel.append(title);if(info.message_queue?.ready===false){const error=document.createElement('p');error.textContent=info.message_queue.detail;panel.append(error);}const unsent=info.messages.filter(x=>['manual_send_required','needs_connection','needs_login','needs_review','failed'].includes(x.status));if(unsent.length){const retry=document.createElement('button');retry.textContent='Review '+unsent.length+' unsent messages';retry.onclick=()=>{selected.clear();transferredBatch=unsent.map(x=>({id:x.listing_id,text:x.text}));for(const x of transferredBatch)if(state.listings.some(r=>r.id===x.id))selected.add(x.id);bulkMessage();};panel.append(retry);}for(const job of info.messages.slice(-30)){const line=document.createElement('p');line.textContent=job.title+': '+job.status+(job.detail?' — '+job.detail:'');if(job.status==='delivery_unconfirmed'){const review=document.createElement('button');review.textContent='Record verified delivery';review.onclick=()=>reviewDelivery(job);line.append(document.createTextNode(' '),review);}panel.append(line);}}catch(e){}},10000);
// Emailing links is separate from messaging sellers through their platforms.
emailDigest=function(){
 const rows=state.listings.filter(x=>selected.has(x.id));if(!rows.length)return alert('Select the ads whose links you want to email.');
 closeModal();const overlay=document.createElement('div');overlay.className='modal-back';overlay.id='modal';overlay.innerHTML='<div class="modal" role="dialog"><button class="close" onclick="closeModal()">×</button><h2>Email '+rows.length+' selected ad links</h2><p>This emails your shortlist to a recipient you choose. It does not contact sellers. Sending takes place in your email app.</p><label>Recipient email<input id="digest-to" type="email" placeholder="you@example.com"></label><textarea id="digest-body" rows="12"></textarea><button id="digest-open">Open draft in email app</button><button id="digest-download">Download email draft</button><p id="digest-status" role="status" aria-live="polite"></p></div>';document.body.append(overlay);
 const body=rows.map(x=>x.title+' — '+(x.price||'Price unknown')+'\n'+x.url).join('\n\n');overlay.querySelector('#digest-body').value=body;
 const status=overlay.querySelector('#digest-status');
 overlay.querySelector('#digest-open').onclick=()=>{const to=overlay.querySelector('#digest-to');if(!to.value||!to.checkValidity()){status.textContent='Enter a valid recipient email address.';return;}const url='mailto:'+encodeURIComponent(to.value)+'?subject='+encodeURIComponent('Chris List: selected ads')+'&body='+encodeURIComponent(overlay.querySelector('#digest-body').value);if(url.length>1800){status.textContent='This shortlist is too long for a reliable email-app link. Download the email draft, then open it in your email app to send.';return;}status.textContent='Email draft requested. Nothing has been sent by Chris List. If your email app does not open, use Download email draft.';location.href=url;};
 overlay.querySelector('#digest-download').onclick=()=>{const to=overlay.querySelector('#digest-to');if(!to.value||!to.checkValidity()){status.textContent='Enter a valid recipient email address.';return;}const content='To: '+to.value.replace(/[\r\n]/g,'')+'\r\nSubject: Chris List selected ads\r\nX-Unsent: 1\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n'+overlay.querySelector('#digest-body').value.replace(/\r?\n/g,'\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'message/rfc822'}));a.download='chris-list-selected-ads.eml';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status.textContent='Draft downloaded. Open it in your email app, review it, and send there.';};
};


function showAlertHealth(info){
 if(!info)return;
 let panel=document.querySelector('#automatic-alert-health');
 if(!panel){panel=document.createElement('details');panel.id='automatic-alert-health';document.querySelector('.bar').append(panel);}
 panel.replaceChildren();
 const title=document.createElement('summary');title.textContent='Automatic email & text alerts'+(info.needs_attention?' — needs attention':'');panel.append(title);
 const note=document.createElement('p');note.textContent='Queued alerts retry every 15 minutes while the Mac is awake. Submitted means Mail or Messages accepted the digest; inbox delivery is separate.';panel.append(note);
 if(info.error){const p=document.createElement('p');p.textContent=info.error;panel.append(p);}
 for(const channel of info.channels||[]){
  const p=document.createElement('p'),c=channel.counts;
  p.textContent=channel.name+': '+(!channel.enabled?'disabled':!channel.configured?'needs configuration':(c.pending+c.failed)+' queued, '+c.held+' need review, '+c.submitting+' submitting')+(channel.last_submission?' · last submitted '+new Date(channel.last_submission).toLocaleString():'');panel.append(p);
 }
}

function reviewDelivery(job){
 closeModal();
 const overlay=document.createElement('div');overlay.className='modal-back';overlay.id='modal';
 overlay.innerHTML='<div class="modal" role="dialog"><button class="close" onclick="closeModal()">×</button><h2>Verify seller delivery</h2><p>Open the seller conversation and check this exact message. An empty inbox alone does not prove a send failed. If delivery is still uncertain, close this form and leave it on hold.</p><a id="delivery-link" target="_blank" rel="noopener">Open listing</a><pre id="delivery-text"></pre><form id="delivery-review"><label>Checked by<input name="reviewer" required></label><label>Verified outcome<select name="outcome" required><option value="">Choose after checking</option><option value="sent">Exact outgoing message is in this seller conversation</option><option value="not_sent">Verified that no message was sent</option></select></label><label>Evidence<textarea name="evidence" required placeholder="Describe the matching conversation, time, delivery indicator or explicit send failure."></textarea></label><label><input name="confirmed" type="checkbox" required> I checked this listing, seller and exact message.</label><button>Save delivery record</button><p class="small">A verified failed send will require a fresh listing review and approval before retrying.</p><p id="delivery-result" role="status"></p></form></div>';
 document.body.append(overlay);overlay.querySelector('#delivery-link').href=job.url;overlay.querySelector('#delivery-text').textContent=job.text;
 const form=overlay.querySelector('form');form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button'),status=overlay.querySelector('#delivery-result');button.disabled=true;try{const fields=new FormData(form);const result=await localCall('message-reconcile',{id:job.id,url:job.url,text:job.text,reviewer:fields.get('reviewer'),outcome:fields.get('outcome'),evidence:fields.get('evidence'),confirmed:fields.has('confirmed')});status.textContent=result.message.status==='sent'?'Delivery recorded. This message will not be resent.':'Verified failure recorded. Review the listing and approve a new attempt from the delivery status panel.';}catch(error){status.textContent=error.message;button.disabled=false;}};
}

function showStaffRequests(info){
 let panel=document.querySelector('#staff-requests');if(!panel){panel=document.createElement('details');panel.id='staff-requests';document.querySelector('.bar').append(panel);}panel.replaceChildren();
 const title=document.createElement('summary');title.textContent='Staff listing requests';panel.append(title);
 const attached=new Set((info.messages||[]).map(x=>x.review?.staff_request?.event_id).filter(Boolean));
 for(const request of (info.staff_requests||[]).slice(-30)){
  const line=document.createElement('p');line.textContent=(request.staff||'Staff')+': '+request.exact_staff_text+' — '+(attached.has(request.event_id)?'Linked to reviewed seller message':request.status==='needs_approval'?'Needs listing and exact-message approval':'Needs a specific listing');
  if(request.status==='needs_approval'&&!attached.has(request.event_id)){
   const button=document.createElement('button');button.textContent='Review request';button.onclick=()=>{const row=state.listings.find(x=>x.id===request.listing_id&&x.url===request.listing_url&&x.title===request.listing_title);if(!row)return alert('The listing changed or is unavailable. Resolve the request before sending.');selected.clear();selected.add(row.id);transferredBatch=[{id:row.id,staff_event:request.event_id,staff_text:request.exact_staff_text}];bulkMessage();};line.append(document.createTextNode(' '),button);
  }panel.append(line);
 }
}
