// Local-model conversation, ad galleries, and explicit bulk message submissions.
let localService=false;
let conversation=JSON.parse(localStorage.getItem('chris-conversation')||'[]');
let transferredBatch=null;
if(location.hash.startsWith('#message-batch=')){try{transferredBatch=JSON.parse(decodeURIComponent(location.hash.slice(15)));history.replaceState(null,'',location.pathname);}catch(e){}}
let searchSpec=JSON.parse(localStorage.getItem('chris-search-spec')||'null');
const localAppURL='http://kms-mac-mini-1.tail016811.ts.net:8766/';
async function localCall(path,data){
 const response=await originalFetch('/local/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-Chris-List':'local'}:{},body:data?JSON.stringify(data):undefined});
 if(!response.ok)throw Error((await response.json()).error||'Mac service unavailable');return response.json();
}
function saveChat(){localStorage.setItem('chris-conversation',JSON.stringify(conversation));localStorage.setItem('chris-search-spec',JSON.stringify(searchSpec));}
function chatPanel(){
 const panel=document.createElement('div');panel.className='panel';panel.id='search-assistant';
 panel.innerHTML='<b>What do you want to find?</b><p class="small">Describe the item and your must-haves. Refine the search together, then approve it.</p><div id="chat-history"></div><form id="chat-form"><textarea id="chat-input" required placeholder="I need a machine that holds a pen and cutter together, fits inside…"></textarea><button '+(!localService?'disabled':'')+'>Discuss with local AI</button></form><p class="small" id="chat-status"></p><div id="search-review"></div>';
 const history=panel.querySelector('#chat-history');for(const message of conversation){const p=document.createElement('p');p.textContent=(message.role==='user'?'You: ':'Chris List: ')+message.content;history.append(p);}
 panel.querySelector('#chat-status').innerHTML=localService?'Runs on this Mac with Ollama. No paid AI tokens; chat works without internet.':'<a href="'+localAppURL+'">Open the Mac app for local AI and sending</a> (Tailscale connected), or <a href="http://127.0.0.1:8766/">open directly on this Mac</a>. The public site shows saved scan results.';
 panel.querySelector('#chat-form').onsubmit=async e=>{e.preventDefault();const input=panel.querySelector('#chat-input'),button=panel.querySelector('button'),status=panel.querySelector('#chat-status');const text=input.value.trim();if(!text)return;conversation.push({role:'user',content:text});saveChat();input.value='';button.disabled=true;status.textContent='Local model is thinking…';try{const result=await localCall('assistant',{messages:conversation});conversation.push({role:'assistant',content:result.reply});searchSpec=result.spec;saveChat();await load();}catch(error){status.textContent=error.message;button.disabled=false;}};
 if(searchSpec){const review=panel.querySelector('#search-review');review.innerHTML='<h3>Review search</h3><label>Marketplace keywords<input id="spec-query"></label><label>All requirements<textarea id="spec-description"></textarea></label><label>Required phrases (comma separated)<input id="spec-include"></label><label>Exclude phrases (comma separated)<input id="spec-exclude"></label><label>Hide asking prices above $ (optional)<input id="spec-max" type="number" min="0"></label><label>Priority<select id="spec-priority"><option value="primary">Primary</option><option value="secondary">Lower priority</option></select></label><p class="small">Keywords, required/excluded phrases and price limit are enforced. Other specifics stay attached for verification; they are not assumed true.</p><button id="approve-search">Approve and start searching</button><button id="new-search">Start another search</button>';
 for(const [id,value] of [['query',searchSpec.query],['description',searchSpec.description],['include',(searchSpec.include||[]).join(', ')],['exclude',(searchSpec.exclude||[]).join(', ')],['max',searchSpec.price_max??''],['priority',searchSpec.priority||'primary']])review.querySelector('#spec-'+id).value=value||'';
 review.querySelector('#approve-search').onclick=async()=>{try{const value=id=>review.querySelector('#spec-'+id).value;const spec={query:value('query'),description:value('description'),include:value('include').split(',').map(s=>s.trim()).filter(Boolean),exclude:value('exclude').split(',').map(s=>s.trim()).filter(Boolean),price_max:value('max')===''?null:Number(value('max')),priority:value('priority')};await localCall('watch',spec);await api('/api/watch',{description:spec.description||spec.query});const result=await localCall('scan',{});alert(result.status);conversation=[];searchSpec=null;saveChat();load();}catch(e){alert(e.message);}};
 review.querySelector('#new-search').onclick=()=>{conversation=[];searchSpec=null;saveChat();load();};}
 return panel;
}
function bulkMessage(){
 closeModal();const rows=state.listings.filter(x=>selected.has(x.id));if(!rows.length)return alert('Select one or more ads first.');
 const overlay=document.createElement('div');overlay.className='modal-back';overlay.id='modal';overlay.innerHTML='<div class="modal" role="dialog"><button class="close" onclick="closeModal()">×</button><h2>Message '+rows.length+' selected ads</h2><label>Message option<select id="bulk-option"><option value="free">Free pickup for art project</option><option value="offer">Make an offer</option><option value="tools">Ask about pen + cutter</option><option value="custom">Write my own</option></select></label><label>Offer amount<input id="bulk-offer" type="number" min="0"></label><textarea id="bulk-template"></textarea><p class="small">Use {title} and {offer}. Edit any individual message below.</p><button id="apply-template">Apply to selected ads</button><div id="bulk-previews"></div><button id="send-batch">Send selected Facebook messages</button><p id="bulk-result" class="small"></p></div>';document.body.append(overlay);
 const template=overlay.querySelector('#bulk-template');
 const templates={free:'Hi! I’m building a local art project. If this is still available and you mainly need it out of the way, I’d love to pick it up free. Please keep me in mind if it doesn’t sell.',offer:'Hi! I’m interested in your {title} for an art project. Would you consider ${offer}? I can arrange pickup.',tools:'Hi! Does your {title} hold a pen and cutter at the same time and draw then cut without manually swapping tools? Are both tools included? Could you confirm the working width and overall machine width?',custom:''};
 function apply(){const amount=overlay.querySelector('#bulk-offer').value;overlay.querySelector('#bulk-previews').replaceChildren();for(const row of rows){const div=document.createElement('div');div.className='message-preview';const label=document.createElement('p');label.textContent=row.platform+' · '+row.title;const text=document.createElement('textarea');text.dataset.listing=row.id;text.value=template.value.replaceAll('{title}',row.title).replaceAll('{offer}',amount||'[offer amount]');const copy=document.createElement('button');copy.textContent='Copy message';copy.onclick=()=>copyText(text.value);const open=document.createElement('a');open.href=row.url;open.target='_blank';open.rel='noopener';open.textContent='Open ad';div.append(label,text,copy,open);overlay.querySelector('#bulk-previews').append(div);}}
 template.value=templates.free;apply();if(transferredBatch){for(const t of overlay.querySelectorAll('[data-listing]')){const item=transferredBatch.find(x=>x.id===t.dataset.listing);if(item)t.value=item.text;}transferredBatch=null;}overlay.querySelector('#bulk-option').onchange=e=>{template.value=templates[e.target.value];apply();};overlay.querySelector('#apply-template').onclick=apply;
 overlay.querySelector('#send-batch').onclick=async()=>{const out=overlay.querySelector('#bulk-result');if(!localService){const batch=[...overlay.querySelectorAll('[data-listing]')].map(t=>({id:t.dataset.listing,text:t.value}));const link=document.createElement('a');link.href=localAppURL+'#message-batch='+encodeURIComponent(JSON.stringify(batch));link.textContent='Continue with these messages on your Mac';out.replaceChildren(link);return;}try{const messages=[...overlay.querySelectorAll('[data-listing]')].map(t=>({id:t.dataset.listing,text:t.value}));if(messages.some(x=>!x.text.trim()||x.text.includes('[offer amount]')))throw Error('Fill in the offer and message before sending.');const result=await localCall('messages',{messages});out.textContent=result.messages.map(x=>x.title+': '+x.status).join('\n');}catch(e){out.textContent=e.message;}};
}
async function copyText(text){if(navigator.clipboard){await navigator.clipboard.writeText(text);return;}const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();document.execCommand('copy');t.remove();}
const workspaceRender=render;
render=function(){workspaceRender();const aside=document.querySelector('aside');aside.prepend(chatPanel());const watch=aside.querySelector('#wf')?.closest('.panel');if(watch){const heading=watch.querySelector('b');if(heading)heading.textContent='Quick keyword search';if(localService){watch.querySelector('#wf').onsubmit=async e=>{e.preventDefault();const query=watch.querySelector('#desc').value.trim();try{await localCall('watch',{query,description:query});await api('/api/watch',{description:query});await localCall('scan',{});load();}catch(err){alert(err.message);}};for(const b of watch.querySelectorAll('button'))if(b.textContent==='Add description to automatic scans')b.remove();}}
 const old=document.querySelector('.bar button');for(const b of document.querySelectorAll('.bar button'))if(b.textContent==='review selected messages'){b.textContent='Message selected ads';b.onclick=bulkMessage;}
 const all=document.createElement('button');all.textContent='Select all primary ads';all.onclick=()=>{state.listings.filter(x=>x.priority!=='secondary'&&x.status!=='passed').forEach(x=>selected.add(x.id));load();};document.querySelector('.bar').append(all);const none=document.createElement('button');none.textContent='Clear selection';none.onclick=()=>{selected.clear();load();};document.querySelector('.bar').append(none);
 if(localService&&transferredBatch){for(const x of transferredBatch)if(state.listings.some(r=>r.id===x.id))selected.add(x.id);if(selected.size)setTimeout(bulkMessage,0);}
 if(localService){const connection=document.createElement('button');connection.textContent='Check Facebook sending connection';connection.onclick=async()=>{connection.disabled=true;try{const info=await localCall('chrome-check',{});alert(info.login_required?'Chrome connection works; sign in to Facebook in Chrome before sending.':'Chrome connection works. Facebook opened without a password form; review your selected messages before sending.');}catch(e){alert(e.message);}finally{connection.disabled=false;}};document.querySelector('.bar').append(connection);const scan=document.createElement('button');scan.textContent='Scan now on this Mac';scan.onclick=async()=>{try{alert((await localCall('scan',{})).status);}catch(e){alert(e.message);}};document.querySelector('.bar').append(scan);}
};
const galleryOpen=openItem;
openItem=function(id){galleryOpen(id);const modal=document.querySelector('.modal');if(!modal)return;const row=state.listings.find(x=>x.id===id);const selectedBox=document.createElement('label');const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.style.width='auto';checkbox.checked=selected.has(id);checkbox.onchange=()=>checkbox.checked?selected.add(id):selected.delete(id);selectedBox.append(checkbox,document.createTextNode(' Select this ad for messaging'));modal.prepend(selectedBox);const message=document.createElement('button');message.textContent='Message this ad';message.onclick=()=>{selected.clear();selected.add(id);bulkMessage();};selectedBox.after(message);
 const gallery=document.createElement('div');gallery.className='ad-gallery';const status=document.createElement('p');status.className='small';const known=row.images?.length?row.images:row.image?[row.image]:[];function show(images){gallery.replaceChildren();for(const src of [...new Set(images)]){if(!/^https?:\/\//.test(src))continue;const a=document.createElement('a');a.href=src;a.target='_blank';a.rel='noopener';const img=document.createElement('img');img.src=src;img.alt=row.title;img.loading='lazy';a.append(img);gallery.append(a);}}show(known);modal.querySelector('.detail').after(gallery,status);
 status.textContent=row.photo_status||'Search photo only; fetching the ad gallery requires the Mac app.';
 if(localService){status.textContent='Loading ad photos…';localCall('photos?id='+encodeURIComponent(id)).then(async data=>{show(data.images);status.textContent=data.detail;await api('/api/listing/update',{id,images:data.images,photo_status:data.detail});}).catch(e=>status.textContent='Gallery unavailable: '+e.message);}
};
localCall('status').then(()=>{localService=true;load();}).catch(()=>{});
setInterval(async()=>{if(!localService||document.visibilityState!=='visible')return;try{const info=await localCall('status');let panel=document.querySelector('#delivery-status');if(!panel){panel=document.createElement('details');panel.id='delivery-status';document.querySelector('.bar').append(panel);}panel.replaceChildren();const title=document.createElement('summary');title.textContent='Message delivery status';panel.append(title);for(const job of info.messages.slice(-30)){const line=document.createElement('p');line.textContent=job.title+': '+job.status+(job.detail?' — '+job.detail:'');panel.append(line);}}catch(e){}},10000);
